name: ROS2 Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    steps:

      - name: Check out ubc-subbots/triton
        uses: actions/checkout@v2

      - name: Setup ROS2 distro and system deps
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Install deps with rosdep
        run: |
          rosdep update
          rosdep install -i --from-path src --rosdistro jazzy -y

- name: Install opencv
  uses: cvpkg/opencv-action@v0.1
  with:
    opencv_tag: '4.10.0' # Optional. Default is '4.6.0'. An env var 'opencv_tag' will be defined.
    BUILD_LIST: 'core,imgcodecs,imgproc' # Optional. Default is 'core,imgcodecs,imgproc'. The opencv modules(libraries, components) to be build, separated with `,` and no spaces.
    BUILD_SHARED_LIBS: 'OFF' # Optional. Default is 'OFF'. Build shared opencv librarires, should be "ON" or "OFF".
    BUILD_WITH_STATIC_CRT: 'OFF' # Optional. Default is 'OFF'. Build with static C Runtime Library?(only when MSVC), should be "ON" or "OFF"


      - name: Ignore with colcon build
        run: |
          touch ./opencv-install/COLCON_IGNORE

      - name: Source setup and build then test using colcon
        env:
          LD_LIBRARY_PATH: /usr/local/lib/
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --cmake-args -DCMAKE_CXX_STANDARD=14
          source ./install/setup.bash
          colcon test
          colcon test-result --verbose
