name: ROS2 Build and Test CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out ubc-subbots/triton
        uses: actions/checkout@v2

      - name: Setup ROS2 distro and system deps
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Install deps with rosdep
        run: |
          rosdep update
          rosdep install -i --from-path src --rosdistro jazzy -y

      - name: Cache OpenCV
        id: opencv-cache
        uses: actions/cache@v4
        with:
          path: ./opencv-install
          key: ${{ runner.os }}-opencv-cache

      - name: Install OpenCV
        uses: rayandrews/with-opencv-action@v1
        with:
          dir: ./opencv-install
          cached: ${{ steps.opencv-cache.outputs.cache-hit }}
          opencv-version: '4.10.0'
          CMAKE_BUILD_TYPE: RELEASE
          ENABLE_PRECOMPILED_HEADERS: OFF

      - name: Ignore with colcon build
        run: |
          touch ./opencv-install/COLCON_IGNORE

      - name: test package
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: doe_control
          target-ros2-distro: jazzy


