name: ROS2 Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    steps:

      - name: Check out ubc-subbots/triton
        uses: actions/checkout@v2

      - name: Setup ROS2 distro and system deps
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Install deps with rosdep
        run: |
          rosdep update
          rosdep install -i --from-path src --rosdistro jazzy -y

      - uses: Dovyski/setup-opencv-action@v1.1
        with:
          opencv-version: '4.10.0'

      - name: Ignore with colcon build
        run: |
          touch ./opencv-install/COLCON_IGNORE

      - name: Source setup and build then test using colcon
        env:
          LD_LIBRARY_PATH: /usr/local/lib/
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --cmake-args -DCMAKE_CXX_STANDARD=14
          source ./install/setup.bash
          colcon test
          colcon test-result --verbose
